# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e7bda499093ec1488578082491c81b551f1b685754bbce2f064b285ca231f08b5051c4bbe302475f6f24b10f975cdfc52ad0d4cae19f8df8a77a7b54f6ed17

test:
  secret_key_base: 7e3170059168e9925dd6a788f28a7f6039347af0c0b5f2562ae5abd9c7b8a4cf81ae6a2aa4d0932e384f4dc9a1d62a6b84a7f83d17809ab2018ed15487c5b510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
